name: Android Build
on:
  push:
    branches:
      - main
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    environment: EAS
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: yarn install
        run: yarn install

      - name: Install eas
        run: npm install -g eas-cli

      - name: Build iOS App
        run: eas build --platform ios --profile preview --non-interactive

      - uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: App is ready for review, you can [see it here](https://expo.dev/@dandelion-aid-app/use-expo?release-channel=pr-${{ github.event.number }}).